<#
.SYNOPSIS
  Release helper: bump version, generate release notes, commit, tag, push,
  optionally build, and publish GitHub release.

.DESCRIPTION
  This script updates the package version in `pyproject.toml` and `purviewcli/__init__.py`,
  updates README occurrences of the old version, creates `releases/v<version>.md` when missing,
  commits the changes, creates an annotated tag `v<version>`, pushes to origin when requested,
  and can run the project's build script and publish the GitHub release.

.USAGE
  # Bump to 1.0.13, commit and tag locally
  .\release.ps1 -NewVersion 1.0.13

  # Bump, commit, tag and push to origin
  # Also creates GitHub release automatically from releases/v<version>.md
  .\release.ps1 -NewVersion 1.0.13 -Push

  # Bump, commit, tag, push and run build_pypi.bat
  .\release.ps1 -NewVersion 1.0.13 -Push -Build

  # Bump, build pvw-cli AND publish pvw-mcp-server to PyPI in one step
  .\release.ps1 -NewVersion 1.0.13 -Push -Build -McpPublish

  # Bump/push but skip GitHub release creation
  .\release.ps1 -NewVersion 1.0.13 -Push -SkipGitHubRelease

  # Explicitly request GitHub release creation (requires -Push)
  .\release.ps1 -NewVersion 1.0.13 -Push -CreateGitHubRelease

.NOTES
  - Recommended to run in PowerShell Core (pwsh). A small batch wrapper is included
    for convenience when using cmd.exe.
  - The script refuses to run if there are uncommitted changes unless -Force is provided.
  - Release notes file `releases/v<version>.md` is auto-generated if it does not exist.
  - When -Push is used, GitHub release creation is enabled by default.
  - Release creation uses scripts/create_github_release.ps1.
#>

param(
    [Parameter(Mandatory=$true, Position=0)][string]$NewVersion,
    [switch]$Push,
    [switch]$Build,
    [switch]$McpPublish,
  [switch]$CreateGitHubRelease,
  [switch]$SkipGitHubRelease,
    [switch]$Force
)

function Write-Info([string]$m) { Write-Host "[INFO] $m" -ForegroundColor Cyan }
function Write-Warn([string]$m) { Write-Host "[WARN] $m" -ForegroundColor Yellow }
function Write-Err([string]$m) { Write-Host "[ERROR] $m" -ForegroundColor Red }

function Resolve-PreviousTag([string]$fallbackVersion) {
  $fallbackTag = "v$fallbackVersion"
  git rev-parse --verify "refs/tags/$fallbackTag" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) {
    return $fallbackTag
  }

  $lastTag = (git tag --sort=-version:refname | Select-Object -First 1)
  if ($lastTag) {
    return $lastTag.Trim()
  }

  return $null
}

function New-ReleaseNotesFile([string]$repoRoot, [string]$newVersion, [string]$oldVersion) {
  $releasesDir = Join-Path $repoRoot 'releases'
  if (-not (Test-Path $releasesDir -PathType Container)) {
    New-Item -ItemType Directory -Path $releasesDir -Force | Out-Null
  }

  $notesPath = Join-Path $releasesDir ("v{0}.md" -f $newVersion)
  if (Test-Path $notesPath -PathType Leaf) {
    Write-Info "Release notes already exist: $notesPath"
    return $notesPath
  }

  $previousTag = Resolve-PreviousTag -fallbackVersion $oldVersion
  $range = $null
  if ($previousTag) {
    $range = "$previousTag..HEAD"
    Write-Info "Generating release notes from range: $range"
  } else {
    Write-Warn "No previous tag found. Generating release notes from recent commits."
  }

  $commitLines = @()
  if ($range) {
    $commitLines = @(git log $range --pretty=format:"- %h %s")
  } else {
    $commitLines = @(git log -n 20 --pretty=format:"- %h %s")
  }
  if (-not $commitLines -or $commitLines.Count -eq 0) {
    $commitLines = @('- Initial release notes entry')
  }

  $changedFiles = @()
  if ($range) {
    $changedFiles = @(git diff --name-only $range)
  }
  if (-not $changedFiles -or $changedFiles.Count -eq 0) {
    $changedFiles = @('No file changes detected in computed range')
  }

  $today = Get-Date -Format 'MMMM d, yyyy'
  $header = @(
    "# Release Notes - v$newVersion",
    "",
    "**Release Date**: $today",
    "**Previous Version**: $oldVersion",
    "",
    "---",
    "",
    "## Overview",
    "",
    "v$newVersion release generated by release automation script.",
    "",
    "---",
    "",
    "## Commits",
    ""
  )

  $filesHeader = @(
    "",
    "---",
    "",
    "## Changed Areas",
    ""
  )

  $fileLines = $changedFiles | ForEach-Object {
    ('- `{0}`' -f $_)
  }

  $contentLines = @()
  $contentLines += $header
  $contentLines += $commitLines
  $contentLines += $filesHeader
  $contentLines += $fileLines
  $content = $contentLines -join "`n"

  $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
  [System.IO.File]::WriteAllText($notesPath, $content, $Utf8NoBomEncoding)
  Write-Info "Release notes generated: $notesPath"

  return $notesPath
}

# Basic semver-ish validation
if (-not ($NewVersion -match '^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9\.]+)?$')) {
    Write-Err "Version '$NewVersion' doesn't look like a semantic version (MAJOR.MINOR.PATCH)."
    exit 2
}

$shouldCreateGitHubRelease = $false
if ($CreateGitHubRelease) {
  $shouldCreateGitHubRelease = $true
} elseif ($Push -and -not $SkipGitHubRelease) {
  # Default behavior: when publishing a release (push), also publish GitHub release.
  $shouldCreateGitHubRelease = $true
}

if ($shouldCreateGitHubRelease -and -not $Push) {
  Write-Err "GitHub release creation requires -Push so the tag exists on origin."
  exit 15
}

# Ensure git is available
try { git --version | Out-Null } catch { Write-Err "git is not available on PATH"; exit 3 }

$repoRoot = (git rev-parse --show-toplevel) 2>&1
if ($LASTEXITCODE -ne 0) { Write-Err "Not inside a git repository."; exit 4 }
$repoRoot = $repoRoot.Trim()
Set-Location $repoRoot

# Ensure working tree is clean unless forced
$status = git status --porcelain
if ($status -and -not $Force) {
    Write-Err "Working tree is not clean. Commit or stash changes first, or run with -Force to override."
    git status --short
    exit 5
}

# Paths
$pyproject = Join-Path $repoRoot 'pyproject.toml'
$initFile = Join-Path $repoRoot 'purviewcli\__init__.py'
$readme = Join-Path $repoRoot 'README.md'
$releaseNotesFile = Join-Path (Join-Path $repoRoot 'releases') ("v{0}.md" -f $NewVersion)

if (-not (Test-Path $pyproject -PathType Leaf)) { Write-Err "pyproject.toml not found at $pyproject"; exit 6 }
if (-not (Test-Path $initFile -PathType Leaf)) { Write-Err "__init__.py not found at $initFile"; exit 6 }

Write-Info "Reading current version from purviewcli/__init__.py..."
$versionMatch = [regex]::Match((Get-Content -Raw -Path $initFile), '__version__\s*=\s*"([^"]+)"')
if (-not $versionMatch.Success) {
  Write-Err "Could not find __version__ in $initFile"
  exit 7
}
$oldVersion = $versionMatch.Groups[1].Value
Write-Info "Current version: $oldVersion -> New version: $NewVersion"

if ($oldVersion -eq $NewVersion) { Write-Warn "New version is identical to current version. Nothing to do."; exit 0 }

function Backup-File($path) {
  $bak = "$path.bak"
  if (Test-Path $bak) {
    $ts = Get-Date -Format yyyyMMddHHmmss
    $bak = "$path.bak.$ts"
  }
  Copy-Item -Force -Path $path -Destination $bak
  Write-Info "Backup created: $bak"
}

Backup-File $initFile
if (Test-Path $readme) { Backup-File $readme }

Write-Info "Updating purviewcli/__init__.py..."
# Read file as lines and replace the __version__ line or insert at top if missing
$lines = (Get-Content -Path $initFile -Encoding UTF8)
$found = $false
for ($i = 0; $i -lt $lines.Count; $i++) {
  if ($lines[$i] -match '^[ \t]*__version__\s*=') {
    $lines[$i] = "__version__ = `"$NewVersion`""
    $found = $true
    break
  }
}
if (-not $found) {
  # insert at top
  $lines = ,("__version__ = `"$NewVersion`"" ) + $lines
}
# Write back with UTF8 encoding without BOM
$content = $lines -join "`n"
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
[System.IO.File]::WriteAllText($initFile, $content, $Utf8NoBomEncoding)

if (Test-Path $readme) {
    Write-Info "Updating README.md occurrences of version..."
    # Read with explicit UTF8 encoding to preserve Unicode characters (emojis, etc.)
    $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
    $readmeText = [System.IO.File]::ReadAllText($readme, $Utf8NoBomEncoding)
    # Replace v<oldVersion> and PVW CLI v<oldVersion>
    $r = $readmeText -replace [regex]::Escape("v$oldVersion"), "v$NewVersion"
    $r = $r -replace [regex]::Escape("PVW CLI v$oldVersion"), "PVW CLI v$NewVersion"
    # Write back with UTF8 encoding without BOM (preserves all Unicode characters)
    [System.IO.File]::WriteAllText($readme, $r, $Utf8NoBomEncoding)
}

# ---------------------------------------------------------------------------
# MCP server version sync (always runs, commit included in the same release commit)
# ---------------------------------------------------------------------------
$mcpRoot = Join-Path $repoRoot 'tools\PurviewMCPServer'
$mcpVersionFile  = Join-Path $mcpRoot '__version__.py'
$mcpPyproject    = Join-Path $mcpRoot 'pyproject.toml'
$mcpFilesChanged = @()

if (Test-Path $mcpVersionFile -PathType Leaf) {
    Write-Info "Updating MCP server __version__.py to $NewVersion..."
    $mcpVerLines = Get-Content -Path $mcpVersionFile -Encoding UTF8
    $mcpVerFound = $false
    for ($i = 0; $i -lt $mcpVerLines.Count; $i++) {
        if ($mcpVerLines[$i] -match '^[ \t]*__version__\s*=') {
            $mcpVerLines[$i] = "__version__ = `"$NewVersion`""
            $mcpVerFound = $true
            break
        }
    }
    if ($mcpVerFound) {
        $mcpVerContent = $mcpVerLines -join "`n"
        $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
        [System.IO.File]::WriteAllText($mcpVersionFile, $mcpVerContent, $Utf8NoBomEncoding)
        $mcpFilesChanged += $mcpVersionFile
        Write-Info "MCP __version__.py updated."
    } else {
        Write-Warn "Could not find __version__ line in $mcpVersionFile — skipping."
    }
} else {
    Write-Warn "MCP __version__.py not found at $mcpVersionFile — skipping version sync."
}

if (Test-Path $mcpPyproject -PathType Leaf) {
    Write-Info "Updating pvw-cli dependency in MCP pyproject.toml to >=$NewVersion..."
    $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
    $mcpToml = [System.IO.File]::ReadAllText($mcpPyproject, $Utf8NoBomEncoding)
    # Replace pvw-cli>=<any version> with pvw-cli>=$NewVersion
    $mcpToml = $mcpToml -replace 'pvw-cli>=([0-9]+\.[0-9]+\.[0-9]+)', "pvw-cli>=$NewVersion"
    [System.IO.File]::WriteAllText($mcpPyproject, $mcpToml, $Utf8NoBomEncoding)
    $mcpFilesChanged += $mcpPyproject
    Write-Info "MCP pyproject.toml pvw-cli dependency updated."
}

  $releaseNotesFile = New-ReleaseNotesFile -repoRoot $repoRoot -newVersion $NewVersion -oldVersion $oldVersion

# Verify package builds before committing
Write-Info "Verifying package can be built before committing..."
$buildScriptPS = Join-Path (Join-Path $repoRoot 'scripts') 'build_pypi.ps1'
if (Test-Path $buildScriptPS) {
  Write-Info "Running build verification script: $buildScriptPS (no upload)"
  # Prefer pwsh if available, otherwise invoke using the current PowerShell
  $pwshCmd = Get-Command pwsh -ErrorAction SilentlyContinue
  if ($pwshCmd) {
    & $pwshCmd.Source -NoProfile -ExecutionPolicy Bypass -File $buildScriptPS
  } else {
    # already in PowerShell; run script directly
    & $buildScriptPS
  }
  if ($LASTEXITCODE -ne 0) {
    Write-Err "Build verification failed. Aborting release. See build output above for details."
    exit 14
  }
  Write-Info "Build verification succeeded. Proceeding to commit and tagging."
} else {
  Write-Warn "Build verification script not found at $buildScriptPS - skipping build verification."
}

Write-Info "Staging changes..."
$filesToStage = @($initFile, $releaseNotesFile) + $mcpFilesChanged
if (Test-Path $readme) { $filesToStage += $readme }
git add $filesToStage
if ($LASTEXITCODE -ne 0) { Write-Err "git add failed"; exit 8 }

$commitMsg = "Bump version to $NewVersion"
Write-Info "Committing: $commitMsg"
git commit -m $commitMsg --no-verify
if ($LASTEXITCODE -ne 0) { Write-Err "git commit failed"; git status --short; exit 9 }

Write-Info "Creating annotated tag v$NewVersion"
git tag -a "v$NewVersion" -m "Release v$NewVersion"
if ($LASTEXITCODE -ne 0) { Write-Err "git tag failed"; exit 10 }

if ($Push) {
    Write-Info "Pushing commit to origin..."
    git push origin HEAD
    if ($LASTEXITCODE -ne 0) { Write-Err "git push failed"; exit 11 }

    Write-Info "Pushing tag v$NewVersion to origin..."
    git push origin "v$NewVersion"
    if ($LASTEXITCODE -ne 0) { Write-Err "git push tag failed"; exit 12 }
}

if ($Build) {
  # Prefer PowerShell build script (build_pypi.ps1); fall back to batch if missing
  $buildScriptPS = Join-Path (Join-Path $repoRoot 'scripts') 'build_pypi.ps1'
  if (Test-Path $buildScriptPS) {
    Write-Info "Running PowerShell build script: $buildScriptPS"
    $pwshCmd = Get-Command pwsh -ErrorAction SilentlyContinue
    if ($pwshCmd) {
      & $pwshCmd.Source -NoProfile -ExecutionPolicy Bypass -File $buildScriptPS
    } else {
      & $buildScriptPS
    }
    if ($LASTEXITCODE -ne 0) { Write-Err "PowerShell build script failed with exit code $LASTEXITCODE"; exit 13 }
  } else {
    $buildScript = Join-Path $repoRoot 'build_pypi.bat'
    if (Test-Path $buildScript) {
      Write-Info "PowerShell build script not found; falling back to batch: $buildScript"
      & cmd /c $buildScript
      if ($LASTEXITCODE -ne 0) { Write-Err "Batch build script failed with exit code $LASTEXITCODE"; exit 13 }
    } else {
      Write-Warn "No build script found: checked scripts\build_pypi.ps1 and build_pypi.bat"
    }
  }
}

# ---------------------------------------------------------------------------
# MCP server PyPI publish (runs after the main pvw-cli build, when -McpPublish)
# ---------------------------------------------------------------------------
if ($McpPublish) {
    $mcpBuildScript = Join-Path $mcpRoot 'build_pypi.ps1'
    if (-not (Test-Path $mcpBuildScript -PathType Leaf)) {
        Write-Err "MCP build script not found at $mcpBuildScript"
        exit 18
    }
    Write-Info "Building and publishing pvw-mcp-server $NewVersion to PyPI..."
    $pwshCmd = Get-Command pwsh -ErrorAction SilentlyContinue
    if ($pwshCmd) {
        & $pwshCmd.Source -NoProfile -ExecutionPolicy Bypass -File $mcpBuildScript -Publish
    } else {
        & $mcpBuildScript -Publish
    }
    if ($LASTEXITCODE -ne 0) {
        Write-Err "MCP server publish failed with exit code $LASTEXITCODE"
        exit 19
    }
    Write-Info "pvw-mcp-server $NewVersion published to PyPI successfully."
}

if ($shouldCreateGitHubRelease) {
  $ghReleaseScript = Join-Path (Join-Path $repoRoot 'scripts') 'create_github_release.ps1'
  if (-not (Test-Path $ghReleaseScript -PathType Leaf)) {
    Write-Err "GitHub release script not found at $ghReleaseScript"
    exit 16
  }

  Write-Info "Creating GitHub release for v$NewVersion..."
  $pwshCmd = Get-Command pwsh -ErrorAction SilentlyContinue
  if ($pwshCmd) {
    & $pwshCmd.Source -NoProfile -ExecutionPolicy Bypass -File $ghReleaseScript -Version $NewVersion
  } else {
    & $ghReleaseScript -Version $NewVersion
  }

  if ($LASTEXITCODE -ne 0) {
    Write-Err "GitHub release creation failed with exit code $LASTEXITCODE"
    exit 17
  }
}

Write-Info "Release steps completed successfully. New tag: v$NewVersion"
exit 0
